services:
  litcoach-api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: litcoach-api
    ports:
      - "8099:8000"
    env_file:
      - .env
    volumes:
      - ./api:/app/api
    restart: unless-stopped
    networks:
      - hilmail-network

networks:
  hilmail-network:
    external: true