services:
  litcoach-api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: litcoach-api
    env_file:
      - .env
    volumes:
      - ./api:/app/api
    restart: unless-stopped
    networks:
      - homelab_network

networks:
  homelab_network:
    external: true